import os
import asyncio
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from datetime import datetime
from core.providers import ModelConfig, ProviderFactory
from memory.db import MemoryDB, MemoryChunk

@dataclass
class Trajectory:
    task_id: str
    prompt: str
    steps: List[Dict[str, Any]]  # List of {tool: str, input: str, output: str}
    final_result: str
    success: bool

class SkillSynthesizer:
    """
    The 'Crystallization' engine. 
    Turns successful tool-call trajectories into reusable .md skills.
    """
    def __init__(self, model_config: ModelConfig, db: MemoryDB, skills_dir: str = "skills"):
        self.provider = ProviderFactory.get_provider(model_config)
        self.db = db
        self.skills_dir = skills_dir
        
        if not os.path.exists(self.skills_dir):
            os.makedirs(self.skills_dir)

    async def synthesize(self, trajectory: Trajectory) -> Optional[str]:
        """
        Analyzes a successful trajectory and creates a concise skill document.
        """
        if not trajectory.success:
            return None

        # Construct a prompt for the LLM to summarize the trajectory into a skill
        steps_summary = "\n".join([
            f"Step {i+1}: {s['tool']}({s['input']}) -> {s['output'][:100]}..." 
            for i, s in enumerate(trajectory.steps)
        ])
        
        synthesis_prompt = (
            f"You are a skill synthesis engine. Analyze the following successful tool trajectory "
            f"and extract the core reusable procedure. \n\n"
            f"Goal: {trajectory.prompt}\n"
            f"Steps:\n{steps_summary}\n"
            f"Final Result: {trajectory.final_result}\n\n"
            f"Create a concise, high-density '.md' skill. Use 'Caveman' style: no fluff, just "
            f"precise steps and constraints. Format as: # Skill Name\\n## Description\\n## Procedure"
        )

        try:
            skill_content = await self.provider.complete(synthesis_prompt, system_prompt="You are an expert in procedural knowledge extraction.")
            
            # Generate a filename based on the goal
            skill_name = trajectory.prompt.replace(" ", "_").lower()[:30] + ".md"
            file_path = os.path.join(self.skills_dir, skill_name)
            
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(skill_content)
            
            # Also index the skill in the MemoryDB for semantic recall
            self.db.add_memory(MemoryChunk(
                content=skill_content,
                embedding=[0.0] * 128, # Embedding would be generated by a real provider
                metadata={"file": file_path, "type": "SKILL"},
                mem_type="DOC"
            ))
            
            return file_path
        except Exception as e:
            print(f"Skill synthesis failed: {e}")
            return None
